name: Build Release
on: 
  push:
    tags:    
      - 'release-**'  
    paths-ignore:
      - 'README.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release with NPM
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.1
    - run: npm install
    - run: |        
        #webpack
        echo $NODE_ENV
        export NODE_ENV="production"
        echo $NODE_ENV
        node node_modules/.bin/webpack
    - run: |    
        #set version number            
        RELEASE_VERSION_NUMBER="$(echo $GITHUB_REF | cut -c19-)"
        echo ${RELEASE_VERSION_NUMBER}
        sed -i -e 's|<version>|'$RELEASE_VERSION_NUMBER'|g' dist-package.json
    - run: |                        
        # copy all staff to distrib
        mkdir distrib
        cp dist/* distrib/
        cp tsOutputs/src/*.d.ts distrib/
        cp tsOutputs/semantic-math-processor-client.d.ts distrib/
        cp dist-package.json distrib/package.json
        cp README.md distrib/README.md
    - run: |               
        #publish to NPM 
        cd distrib
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
        npm publish --access=public
    env:
      NODE_ENV: development
