name: Build
on: 
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with node 
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.1
    - run: npm install
    - run: node node_modules/.bin/tsc -p ./tsconfig.json
    - run: npm run test-ci
    - run: node node_modules/.bin/webpack
