name: Build Release
on: 
  push:
    tags:    
      - 'release-**'  
    paths-ignore:
      - 'README.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release with NPM
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.1
    - run: npm install
    - run: echo $NODE_ENV
    - run: export NODE_ENV="production";echo $NODE_ENV; node node_modules/.bin/webpack
    - run: mkdir distrib
    - run: echo $GITHUB_REF
    - run: RELEASE_VERSION_NUMBER="$(echo $GITHUB_REF | cut -c19-)"; echo ${RELEASE_VERSION_NUMBER}; sed -i -e 's|<version>|'$RELEASE_VERSION_NUMBER'|g' dist-package.json
    # copy all staff to distrib
    - run: cp dist/* distrib/
    - run: cp tsOutputs/src/*.d.ts distrib/
    - run: cp dist-package.json distrib/package.json
    - run: cp README.md distrib/README.md
    - run: cd distrib
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
    - run: npm publish --dry-run --access=public
    env:
      NODE_ENV: development
