name: Document
on: 
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Document with typedoc
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.1
    - run: npm install
    - run: rm -rf docs
    - run: npx typedoc
    - run: touch docs/.nojekyll
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Typedoc"
        git add --all
        git commit -m "Generating documentation" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}    
