name: Test
on: 
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Tests with node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.1
    - run: npm install
    - run: node node_modules/.bin/tsc -p ./tsconfig.json
    - run: npm run test-ci
